--Drop Database if Exists
USE master
IF DB_ID('ipl_curriculum') IS NOT NULL
	DROP DATABASE ipl_curriculum
GO

--Create Database
CREATE DATABASE ipl_curriculum
GO

--Drop Tables That Exist
USE ipl_curriculum
IF OBJECT_ID('EmotDev_ActivityOne') IS NOT NULL
	DROP TABLE EmotDev_ActivityOne
GO
IF OBJECT_ID('EmotDev_ActivityTwo') IS NOT NULL
	DROP TABLE EmotDev_ActivityTwo
GO
IF OBJECT_ID('EmotDev_Wrapup') IS NOT NULL
	DROP TABLE EmotDev_Wrapup
GO
IF OBJECT_ID('IdentDev_ActivityOne') IS NOT NULL
	DROP TABLE IdentDev_ActivityOne
GO
IF OBJECT_ID('IdentDev_ActivityTwo') IS NOT NULL
	DROP TABLE IdentDev_ActivityTwo
GO
IF OBJECT_ID('IdentDev_ActivityThree') IS NOT NULL
	DROP TABLE IdentDev_ActivityThree
GO
IF OBJECT_ID('IdentDev_ActivityFour') IS NOT NULL
	DROP TABLE IdentDev_ActivityFour
GO
IF OBJECT_ID('IdentDev_Legacy') IS NOT NULL
	DROP TABLE IdentDev_Legacy
GO
IF OBJECT_ID('IdentDev_Wrapup') IS NOT NULL
	DROP TABLE IdentDev_Wrapup
GO

--Add Curriculum 
CREATE TABLE EmotDev_ActivityOne(
	SubmissionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Act1 VARCHAR(MAX) NOT NULL,
	Act2 VARCHAR(MAX) NOT NULL,
	Act3 VARCHAR(MAX) NOT NULL,
	Act4 VARCHAR(MAX) NOT NULL,
	LF1 VARCHAR(MAX) NOT NULL,
	LF2 VARCHAR(MAX) NOT NULL
);
GO

CREATE TABLE EmotDev_ActivityTwo(
	SubmissionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Act1 VARCHAR(MAX) NOT NULL,
	Act2 VARCHAR(MAX) NOT NULL,
	Act3 VARCHAR(MAX) NOT NULL,
	LF1 VARCHAR(MAX) NOT NULL
);
GO

CREATE TABLE EmotDev_Wrapup(
	SubmissionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Field1 VARCHAR(MAX) NOT NULL,
	Field2 VARCHAR(MAX) NOT NULL,
	Field3 VARCHAR(MAX) NOT NULL,
	Field4 VARCHAR(MAX) NOT NULL,
	Field5 VARCHAR(MAX) NOT NULL,
	LF1 VARCHAR(MAX) NOT NULL,
	Disc1 VARCHAR(MAX) NOT NULL,
	Disc2 VARCHAR(MAX) NOT NULL,
	Disc3 VARCHAR(MAX) NOT NULL,
	Dsic4 VARCHAR(MAX) NOT NULL,
	Disc5 VARCHAR(MAX) NOT NULL,
	Disc6 VARCHAR(MAX) NOT NULL,
	Act1 VARCHAR(MAX) NOT NULL,
	LF2 VARCHAR(MAX) NOT NULL,
	LF3 VARCHAR(MAX) NOT NULL
);
GO

CREATE TABLE IdentDev_ActivityOne(
	SubmissionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Disc1 VARCHAR(MAX) NOT NULL,
	Disc2 VARCHAR(MAX) NOT NULL,
	Disc3 VARCHAR(MAX) NOT NULL,
	Act1 VARCHAR(MAX) NOT NULL,
	Act2 VARCHAR(MAX) NOT NULL,
	Act3 VARCHAR(MAX) NOT NULL,
	Act4 VARCHAR(MAX) NOT NULL,
	LF1 VARCHAR(MAX) NOT NULL,
	LF2 VARCHAR(MAX) NOT NULL,
	EmotionalCheckup VARCHAR(MAX) NOT NULL
);
GO

CREATE TABLE IdentDev_ActivityTwo(
	SubmissionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Act1 VARCHAR(MAX) NOT NULL,
	Act2 VARCHAR(MAX) NOT NULL,
	Act3 VARCHAR(MAX) NOT NULL,
	LF1 VARCHAR(MAX) NOT NULL,
	EmotionalCheckup VARCHAR(MAX) NOT NULL
);
GO

CREATE TABLE IdentDev_ActivityThree(
	SubmissionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Disc1 VARCHAR(MAX) NOT NULL,
	Disc2 VARCHAR(MAX) NOT NULL,
	Act1 VARCHAR(MAX) NOT NULL,
	Act2 VARCHAR(MAX) NOT NULL,
	Act3 VARCHAR(MAX) NOT NULL,
	LF1 VARCHAR(MAX) NOT NULL,
	LF2 VARCHAR(MAX) NOT NULL,
	EmotionalCheckup VARCHAR(MAX) NOT NULL
);
GO

CREATE TABLE IdentDev_ActivityFour(
	SubmissionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Field1 VARCHAR(MAX) NOT NULL,
	LF1 VARCHAR(MAX) NOT NULL,
	EmotionalCheckup VARCHAR(MAX) NOT NULL
);
GO

CREATE TABLE IdentDev_Legacy(
	SubmissionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Leg1 VARCHAR(MAX) NOT NULL,
	Leg2 VARCHAR(MAX) NOT NULL,
	Leg3 VARCHAR(MAX) NOT NULL,
);
GO

CREATE TABLE IdentDev_Wrapup(
	SubmissionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Field1 VARCHAR(MAX) NOT NULL,
	Field2 VARCHAR(MAX) NOT NULL,
	Field3 VARCHAR(MAX) NOT NULL,
	Field4 VARCHAR(MAX) NOT NULL,
	Field5 VARCHAR(MAX) NOT NULL,
	LF1 VARCHAR(MAX) NOT NULL,
	EmotionalCheckup VARCHAR(MAX) NOT NULL
);
GO